global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "node_exporter"
    static_configs:
      - targets: ["host.docker.internal:9100"]
      
  - job_name: "postgresql_exporter"
    static_configs:
      - targets: ["host.docker.internal:9105"]
      
  - job_name: "redis_exporter"
    static_configs:
      - targets: ["host.docker.internal:9121"]
